"use client";

import { useMemo, useState } from "react";

type InstituteRow = [number, string, string, string, string, string, string, string];
type Institute = {
  no: number;
  code: string;
  name: string;
  place: string;
  region: string;
  type: string;
  minority: string;
  mode: string;
};

const institutes: Institute[] = ([
  [1,"AARM","AAR MAHAVEER ENGINEERING COLLEGE","BANDLAGUDA","HYD","PVT","NA","COED"],
  [2,"ACEG","A C E ENGINEERING COLLEGE (AUTONOMOUS)","GHATKESAR","MDL","PVT","NA","COED"],
  [3,"AITH","ANNAMACHARYA INST OF TECHNOLOGY AND SCI (AUTONOMOUS)","HAYATHNAGAR","RR","PVT","NA","COED"],
  [4,"AIZA","AIZZA COLLEGE OF ENGG AND TECHNOLOGY","MANCHERIAL","MNC","PVT","MUS","COED"],
  [5,"AKIT","ABDULKALAM INST OF TECHNOLOGY AND SCI (AUTONOMOUS)","KOTHAGUDEM","KGM","PVT","NA","COED"],
  [6,"ANRK","ANURAG ENGINEERING COLLEGE (AUTONOMOUS)","KODAD","SRP","PVT","NA","COED"],
  [7,"ANUG","ANURAG UNIVERSITY (FORMERLY ANURAG GRP OF INSTNS- CVSR COLL OF ENGG)","GHATKESAR","MDL","PVT","NA","COED"],
  [8,"ARJN","ARJUN COLLEGE OF TECHNOLOGY AND SCIENCE (AUTONOMOUS)","BATASINGARAM","RR","PVT","NA","COED"],
  [9,"ASRA","AVANTHIS SCIENTIFIC TECH AND RESEARCH ACADEMY","HAYATHNAGAR","RR","PVT","NA","COED"],
  [10,"AURC","AURORA SCIENTIFIC AND TECH RESEARCH ACADEMY","HYDERABAD","HYD","PVT","NA","COED"],
  [11,"AURG","AURORAS SCIENTIFIC AND TECHNOLOGICAL INSTITUTE","GHATKESAR","MDL","PVT","NA","COED"],
  [12,"AURH","RAMAPPA ENGINEERING COLLEGE","SHAYAMPET","HNK","PVT","NA","COED"],
  [13,"AURK","AURORA S TECHNOLOGICAL AND MANAGEMENT ACADEMY","PARVATHAPUR","MDL","PVT","NA","COED"],
  [14,"AURN","AURORAS TECHNOLOGICAL INST","CHIKKADPALLY HYDERABAD","HYD","PVT","NA","COED"],
  [15,"AVIH","AVANTHI INST OF ENGG AND TECHNOLOGY (AUTONOMOUS)","HAYATHNAGAR","RR","PVT","NA","COED"],
  [16,"AVNI","AVN INST OF ENGG &TECHNOLOGY (AUTONOMOUS)","IBRAHIMPATNAM","RR","PVT","NA","COED"],
  [17,"AZAD","AZAD COLLEGE OF ENGINEERING AND TECHNOLOGY","MOINABAD","RR","PVT","MUS","COED"],
  [18,"BIET","BHARAT INSTITUTE OF ENGG AND TECHNOLOGY (AUTONOMOUS)","IBRAHIMPATNAM","RR","PVT","NA","COED"],
  [19,"BITN","BALAJI INSTITUTE OF TECHNOLOGY AND SCI (AUTONOMOUS)","NARSAMPET","WGL","PVT","NA","COED"],
  [20,"BOMA","BOMMA INST OF TECHNOLOGY AND SCI","KHAMMAM","KHM","PVT","NA","COED"],
  [21,"BOSE","ANU BOSE INSTT OF TECHNOLOGY FOR WOMENS (AUTONOMOUS)","PALONCHA","KGM","PVT","NA","GIRLS"],
  [22,"BREW","BHOJREDDY ENGINEERING COLLEGE FOR WOMEN","SAIDABAD","HYD","PVT","NA","GIRLS"],
  [23,"BRIG","BRILLIANT GRAMMAR SCHOOL EDNL SOC GRP OF INSTNS (AUTONOMOUS)","HAYATHNAGAR","RR","PVT","NA","COED"],
  [24,"BRIL","BRILLIANT INSTT OF ENGG AND TECHNOLOGY (AUTONOMOUS)","HAYATHNAGAR","RR","PVT","NA","COED"],
  [25,"BSKR","BHASKAR ENGINEERING COLLEGE","YENKAPALLY","RR","PVT","NA","COED"],
  [26,"BVRI","B V RAJU INSTITUTE OF TECHNOLOGY","NARSAPUR","MED","PVT","NA","COED"],
  [27,"BVRW","BVRIT COLLEGE OF ENGINEERING FOR WOMEN (AUTONOMOUS)","BACHUPALLY","MDL","PVT","NA","GIRLS"],
  [28,"CASR","COLLEGE OF AGRICULTURAL ENGG","SANGAREDDY","SRD","UNIV","NA","COED"],
  [29,"CBIT","CHAITANYA BHARATHI INSTITUTE OF TECHNOLOGY","GANDIPET","RR","PVT","NA","COED"],
  [30,"CDTK","COLLEGE OF DAIRY TECHNOLOGY","KAMAREDDY","KMR","UNIV","NA","COED"],
  [31,"CFSR","COLLEGE OF FOOD SCIENCE AND TECHNOLOGY","RUDRUR","NZB","GOV","NA","COED"],
  [32,"CHET","SRI CHAITANYA TECHNICAL CAMPUS","IBRAHIMPATAN","RR","PVT","NA","COED"],
  [33,"CHTN","SREE CHAITANYA COLLEGE OF ENGINEERING - AUTONOMOUS","KARIMNAGAR","KRM","PVT","NA","COED"],
  [34,"CHTS","SREE CHAITANYA INST OF TECHNOLOGY SCIENCES","KARIMNAGAR","KRM","PVT","NA","COED"],
  [35,"CJIT","CHRISTU JYOTHI INSTITUTE OF TECHNOLOGY AND SCI","JANGAON","JGN","PVT","CHR","COED"],
  [36,"CMRG","CMR TECHNICAL CAMPUS (AUTONOMOUS)","KANDLAKOYA","MDL","PVT","NA","COED"],
  [37,"CMRK","C M R COLLEGE OF ENGG AND TECHNOLOGY - AUTONOMOUS","KANDLAKOYA","MDL","PVT","NA","COED"],
  [38,"CMRM","CMR INSTITUTE OF TECHNOLOGY (AUTONOMOUS)","KANDLAKOYA","MDL","PVT","NA","COED"],
  [39,"CMRN","CMR ENGG COLLEGE (AUTONOMOUS)","KANDLAKOYA","MDL","PVT","NA","COED"],
  [40,"CVRH","CVR COLLEGE OF ENGINEERING","IBRAHIMPATAN","RR","PVT","NA","COED"],
  [41,"DARE","DARIPALLY ANANTHA RAMULU COLLOF ENGGAND TECH","KHAMMAM","KHM","PVT","NA","COED"],
  [42,"DCET","DECCAN COLLEGE OF ENGINEERING AND TECHNOLOGY","DARUSSALAM","HYD","PVT","MUS","COED"],
  [43,"DRKI","D R K INSTITUTE OF SCI AND TECHNOLOGY (AUTONOMOUS)","BOWRAMPET","MDL","PVT","NA","COED"],
  [44,"ELEN","ELLENKI COLLGE OF ENGG AND TECHNOLOGY (AUTONOMOUS)","PATANCHERU","SRD","PVT","NA","COED"],
  [45,"ESUT","EARTH SCIENCES UNIV OF TELANGANA (FORMERLY K U COLLEGE OF ENGG KOTHAGUDEM)","KOTHAGUDEM","KGM","UNIV","NA","COED"],
  [46,"ESUTSF","EARTH SCIENCES UNIV OF TELANGANA (FORMERLY K U COLLEGE OF ENGG KOTHAGUDEM)- SELF FINANCE","KOTHAGUDEM","KGM","SF","NA","COED"],
  [47,"GATE","GATE INSTITUTE OF TECHNOLOGYAND SCIENCES","KODAD","SRP","PVT","NA","COED"],
  [48,"GCTC","GEETANJALI COLLEGE OF ENGG AND TECHNOLOGY (AUTONOMOUS)","KEESARA","MDL","PVT","NA","COED"],
  [49,"GKEM","G K INSTITUTE OF ENGG AND TECH","MAHABUBNAGAR","MBN","PVT","MUS","COED"],
  [50,"GLOB","GLOBAL INST OF ENGINEERING AND TECHNOLOGY (AUTONOMOUS)","CHILKUR","RR","PVT","NA","COED"],
  [51,"GLWC","GOKARAJU LAILAVATHI ENGINEERING COLLEGE","BACHUPALLY","MDL","PVT","NA","COED"],
  [52,"GNIT","GURUNANAK INST OF TECHNOLOGY (AUTONOMOUS)","IBRAHIMPATAN","RR","PVT","NA","COED"],
  [53,"GNTW","G NARAYNAMMA INSTITUTE OF TECHNOLOGY AND SCI","SHAIKPET","HYD","PVT","NA","GIRLS"],
  [54,"GRRR","GOKARAJU RANGARAJU INSTITUTE OF ENGG AND TECH (AUTONOMOUS)","BACHUPALLY","MDL","PVT","NA","COED"],
  [55,"GURU","GURU NANAK INSTITUTIONS TECHNICAL CAMPUS (AUTONOMOUS)","IBRAHIMPATAN","RR","PVT","NA","COED"],
  [56,"HIND","HINDU INSTITUTE OF SCIENCE AND TECHNOLOGY","KUKATPALLY VILLAGE,","MDL","PVT","NA","COED"],
  [57,"HITM","HYDERABAD INST OF TECHNOLOGY AND MGMT (AUTONOMOUS)","MEDCHAL","MDL","PVT","NA","COED"],
  [58,"HOLY","HOLY MARY INSTITUTE OF TECH SCIENCE (AUTONOMOUS)","KEESARA","MDL","PVT","NA","COED"],
  [59,"IARE","INSTITUTE OF AERONAUTICAL ENGINEERING","DUNDIGAL","MDL","PVT","NA","COED"],
  [60,"IITT","INDUR INSTITUTE OF ENGINEERING AND TECHNOLOGY","SIDDIPET","SDP","PVT","NA","COED"],
  [61,"INDI","SRI INDU INSTITUTE OF ENGINEERING AND TECHNOLOGY (AUTONOMOUS)","IBRAHIMPATAN","RR","PVT","NA","COED"],
  [62,"INDU","SRI INDU COLLEGE OF ENGG AND TECHNOLOGY (AUTONOMOUS)","IBRAHIMPATAN","RR","PVT","NA","COED"],
  [63,"ISLC","ISL ENGINEERING COLLEGE (AUTONOMOUS)","BANDLAGUDA","HYD","PVT","MUS","COED"],
  [64,"JAYA","JAYAMUKHI INSTITUTE OF TECHNOLOGY AND SCIS (AUTONOMOUS)","NARSAMPET","WGL","PVT","NA","COED"],
  [65,"JBIT","J B INSTITUTE OF ENGG AND TECHNOLOGY (AUTONOMOUS)","YENKAPALLY","RR","PVT","NA","COED"],
  [66,"JMTS","JYOTHISHMATHI INSTITUTE OF TECHNOLOGY AND SCI (AUTONOMOUS)","KARIMNAGAR","KRM","PVT","NA","COED"],
  [67,"JNKR","JNTUH UNIVERSITY COLLEGE OF ENGINEERING JAGITIAL (AUTONOMOUS)","JAGITIAL","JTL","UNIV","NA","COED"],
  [68,"JNMB","JNTUH UNIVERSITY COLLEGE OF ENGINEERING MAHABUBABAD","MAHABUBABAD","MHB","UNIV","NA","COED"],
  [69,"JNPASF","JNAFAU SCHOOL OF PLANNING AND ARCH - SELF FINANCE","MASABTANK","HYD","SF","NA","COED"],
  [70,"JNPL","JNTUH UNIVERSITY COLLEGE OF ENGINEERING PALAIR","PALAIR","KHM","UNIV","NA","COED"],
  [71,"JNTH","JNTUH UNIVERSITY COLLEGE OF ENGG SCI AND TECH HYDERABAD","HYDERABAD","MDL","UNIV","NA","COED"],
  [72,"JNTHMT","JNTUH UNIVERSITY COLLEGE OF ENGG SCI AND TECH -5 YEAR INTEGRATED MTECH SELF FINANCE","KUKATPALLY","MDL","SF","NA","COED"],
  [73,"JNTM","JNTUH UNIVERSITY COLLEGE OF ENGG MANTHANI","MANTHANI","PDL","UNIV","NA","COED"],
  [74,"JNTR","JNTUH UNIVERSITY COLLEGE OF ENGINEERING RAJANNA SIRCILLA","AGRAHARAM RAJANNA SIRCILLA","SRC","UNIV","NA","COED"],
  [75,"JNTS","JNTUH UNIVERSITY COLLEGE OF ENGINEERING SULTANPUR","SULTANPUR","SRD","UNIV","NA","COED"],
  [76,"JNTSSF","JNTUH UNIVERSITY COLLEGE OF ENGINEERING SULTANPUR - SELF FINANCE","SULTANPUR","SRD","UNIV","NA","COED"],
  [77,"JNWN","JNTUH UNIVERSITY COLLEGE OF ENGINEERING WANAPARTHY","NARSINGAYAPALLY VILLAGE","WNP","UNIV","NA","COED"],
  [78,"JOGI","JOGINPALLY B R ENGINEERING COLLEGE (AUTONOMOUS)","YENKAPALLY","RR","PVT","NA","COED"],
  [79,"JPNE","JAYA PRAKASH NARAYAN COLLEGE OF ENGINEERING (AUTONOMOUS)","MAHABUBNAGAR","MBN","PVT","NA","COED"],
  [80,"JPNH","JAYAPRAKASH NARAYAN ENGINEERING COLLEGE","BANDLAGUDA","HYD","PVT","MUS","COED"],
  [81,"KCEA","KSHATRIYA COLLEGE OF ENGINEERING","ARMOOR","NZB","PVT","NA","COED"],
  [82,"KDDW","KODADA INST OF TECHNOLOGY AND SCIENCE FOR WOMEN","KODADA","SRP","PVT","NA","GIRLS"],
  [83,"KGRH","KG REDDY COLLEGE OF ENGG AND TECHNOLOGY (AUTONOMOUS)","MOINABAD","RR","PVT","NA","COED"],
  [84,"KITS","KAKATIYA INSTITUTE OF TECHNOLOGY AND SCI","WARANGAL","HNK","PVT","NA","COED"],
  [85,"KITW","KAKATIYA INST OF TECHNOLOGY SCI FOR WOMEN","NIZAMABAD","NZB","PVT","NA","GIRLS"],
  [86,"KLRT","KLR COLLEGE OF ENGG AND TECHNOLOGY (AUTONOMOUS)","PALONCHA","KGM","PVT","NA","COED"],
  [87,"KMCE","KESHAV MEMORIAL COLLEGE OF ENGINEERING","IBRAHIMPATAN","RR","PVT","NA","COED"],
  [88,"KMEC","KESHAV MEMORIAL ENGINEERING COLLEGE","KACHWANISINGARAM","MDL","PVT","NA","COED"],
  [89,"KMIT","KESHAV MEMORIAL INST OF TECHNOLOGY (AUTONOMOUS)","NARAYANAGUDA","HYD","PVT","NA","COED"],
  [90,"KNRR","KASIREDDY NARAYAN REDDY COLL ENGG RES (AUTONOMOUS)","HAYATHNAGAR","RR","PVT","NA","COED"],
  [91,"KPRC","KPRIT COLLEGE OF ENGINEERING (AUTONOMOUS)","GHATKESAR","MDL","PVT","NA","COED"],
  [92,"KPRT","KOMMURI PRATAP REDDY INST OF TECHNOLOGY (AUTONOMOUS)","GHATKESAR","MDL","PVT","NA","COED"],
  [93,"KSGI","GOVERNMENT ENGINEERING COLLEGE KOSGI","KOSGI","NPT","GOV","NA","COED"],
  [94,"KTKM","KAMALA INSTITUTE OF TECHNOLOGY AND SCIENCE (AUTONOMOUS)","HUZURABAD","KRM","PVT","NA","COED"],
  [95,"KUEWSF","UNIVERSITY COLLEGE OF ENGG AND TECH FOR WOMEN KU CAMPUS","WARANGAL","HNK","SF","NA","GIRLS"],
  [96,"KUWL","KU COLLEGE OF ENGINEERING AND TECHNOLOGY","WARANGAL","HNK","UNIV","NA","COED"],
  [97,"LRDS","LORDS INSTITUTE OF ENGINEERING AND TECHNOLOGY (AUTONOMOUS)","HIMAYATSAGAR","RR","PVT","MUS","COED"],
  [98,"MDRK","MADHIRA INSTITUTE OF TECHNOLOGY AND SCI","KODAD","SRP","PVT","NA","COED"],
  [99,"METH","METHODIST COLLEGE OF ENGINEERING AND TECHNOLOGY (AUTONOMOUS)","ABIDS","HYD","PVT","NA","COED"],
  [100,"MGHA","MEGHA INST OF ENGG AND TECHNOLOGY FOR WOMEN (AUTONOMOUS)","GHATKESAR","MDL","PVT","NA","GIRLS"],
  [101,"MGIT","MAHATMA GANDHI INSTITUTE OF TECHNOLOGY (AUTONOMOUS)","GANDIPET","RR","PVT","NA","COED"],
  [102,"MGUNSF","MGU COLLEGE OF ENGINEERING AND TECHNOLOGY","NALGONDA","NLG","SF","NA","COED"],
  [103,"MHVR","MAHAVEER INSTITUTE OF SCI AND TECHNOLOGY (AUTONOMOUS)","BANDLAGUDA","HYD","PVT","NA","COED"],
  [104,"MINA","MINA INST OF ENGG AND TECHNOLOGY FOR WOMEN","MIRYALAGUDA","NLG","PVT","NA","GIRLS"],
  [105,"MJCT","M J COLLEGE OF ENGINEERING AND TECHNOLOGY","BANJARA HILLS","HYD","PVT","MUS","COED"],
  [106,"MLID","M L R INSTITUTE OF TECHNOLOGY (AUTONOMOUS)","DUNDIGAL","MDL","PVT","NA","COED"],
  [107,"MLRD","MALLA REDDY COLLEGE OF ENGG TECHNOLOGY (AUTONOMOUS)","MYSAMMAGUDA","MDL","PVT","NA","COED"],
  [108,"MLRS","MARRI LAXMAN REDDY INST OF TECHNOLOGY AND MANAGEMENT (AUTONOMOUS)","DUNDIGAL","MDL","PVT","NA","COED"],
  [109,"MMTZ","MUMTAZ COLL OF ENGG TECHNOLOGY","HYDERABAD","HYD","PVT","MUS","COED"],
  [110,"MOTK","MOTHER TERESA INSTITUTE OF SCI AND TECHNOLOGY (AUTONOMOUS)","SATHUPALLY","KHM","PVT","NA","COED"],
  [111,"MRCE","MALLA REDDY COLLEGE OF ENGINEERING","MYSAMMAGUDA","MDL","PVT","NA","COED"],
  [112,"MRCW","MALLA REDDY ENGG COLLEGE FOR WOMEN (AUTONOMOUS)","MAISAMMAGUDA","MDL","PVT","NA","GIRLS"],
  [113,"MREM","MALLA REDDY ENGINEERING COLLEGE AND MANAGEMENT SCIENCES (AUTONOMOUS)","MEDCHAL","MDL","PVT","NA","COED"],
  [114,"MRTN","ST MARTINS ENGINEERING COLLEGE (AUTONOMOUS)","DHULAPALLY","MDL","PVT","NA","COED"],
  [115,"MTEC","MOTHER THERESA COLLEGE OF ENGG AND TECHNOLOGY","PEDDAPALLY","PDL","PVT","NA","COED"],
  [116,"MVSR","M V S R ENGINEERING COLLEGE (AUTONOMOUS)","NADERGUL","RR","PVT","NA","COED"],
  [117,"NAWB","NAWAB SHAH ALAM KHAN COLL OF ENGG AND TECH (AUTONOMOUS)","NEW MALAKPET","HYD","PVT","MUS","COED"],
  [118,"NGIT","NEIL GOGTE INST OF TECHNOLOGY","KACHIVANI SINGARAM","MDL","PVT","NA","COED"],
  [119,"NNRG","NALLA NARASIMHA REDDY EDNL SOC GRP OF INSTNS (AUTONOMOUS)","GHATKESAR","MDL","PVT","NA","COED"],
  [120,"NRCM","NARSIMHAREDDY ENGINEERING COLLEGE (AUTONOMOUS)","MAISAMMAGUDA","MDL","PVT","NA","COED"],
  [121,"NREC","NALLAMALLA REDDY ENGINEERING COLLEGE (AUTONOMOUS)","GHATKESAR","MDL","PVT","NA","COED"],
  [122,"OUCE","O U COLLEGE OF ENGG HYDERABAD","HYDERABAD","HYD","UNIV","NA","COED"],
  [123,"OUCT","O U COLLEGE OF TECH HYDERABAD","HYDERABAD","HYD","UNIV","NA","COED"],
  [124,"PALV","PALLAVI ENGINEERING COLLEGE (AUTONOMOUS)","KUNTLOOR","RR","PVT","NA","COED"],
  [125,"PETW","PRINCETON INST OF ENGG TECH FOR WOMEN AUTONOMOUS","GHATKESAR","MDL","PVT","NA","GIRLS"],
  [126,"PRIW","PRIYADARSHINI INSTITUTE OF SCIENCE & TECHNOLOGY FOR WOMEN (AUTONOMOUS)","KHAMMAM","KHM","PVT","NA","GIRLS"],
  [127,"PUCE","UNIVERSITY COLLEGE OF ENGINEERING PALAMURU UNIVERSITY","MAHABUBNAGAR","MBN","UNIV","NA","COED"],
  [128,"RITW","RISHI MS INST OF ENGG AND TECH FOR WOMEN - AUTONOMOUS","KUKATPALLY","MDL","PVT","NA","GIRLS"],
  [129,"SAGR","SAGAR GROUP OF INSTITUTIONS","CHEVELLA","VKB","PVT","NA","COED"],
  [130,"SAIS","SAI SPURTHI INSTITUTE OF TECHNOLOGY (AUTONOMOUS)","SATHUPALLY","KHM","PVT","NA","COED"],
  [131,"SANA","SANA ENGINEERING COLLGE","KODAD","SRP","PVT","MUS","COED"],
  [132,"SBIT","SWARNA BHARATHI INSTITUTE OF SCI AND TECHNOLOGY (AUTONOMOUS)","KHAMMAM","KHM","PVT","NA","COED"],
  [133,"SCET","SHADAN COLL OF ENGINEERING AND TECHNOLOGY (AUTONOMOUS)","PEERANCHERU","RR","PVT","MUS","COED"],
  [134,"SCIT","SRI CHAITANYA INSTITUTE OF TECHNOLOGY AND RESEARCH (AUTONOMOUS)","KHAMMAM","KHM","PVT","NA","COED"],
  [135,"SDES","SREE DATTHA INSTITUTE OF ENGINEERING AND SCIENCE (AUTONOMOUS)","IBRAHIMPATAN","RR","PVT","NA","COED"],
  [136,"SDEW","SRIDEVI WOMENS ENGINEERING COLLEGE (AUTONOMOUS)","GANDIPET","RR","PVT","NA","GIRLS"],
  [137,"SDGI","SREE DATTHA GRP OF INSTNS (AUTONOMOUS)","IBRAHIMPATAN","RR","PVT","NA","COED"],
  [138,"SIEI","SIDDHARTHA INSTT OF ENGG AND TECHNOLOGY (AUTONOMOUS)","IBRAHIMPATAN","RR","PVT","NA","COED"],
  [139,"SISG","SIDDHARTHA INSTT OF TECHNOLOGY AND SCIENCES (AUTONOMOUS)","GHATKESAR","MDL","PVT","NA","COED"],
  [140,"SMED","ST MARYS GROUP OF INSTITUTIONS AUTONOMOUS","DESHMUKHI","YBG","PVT","CHR","COED"],
  [141,"SMSK","SAMSKRUTHI COLLEGE OF ENGG AND TECHNOLOGY (AUTONOMOUS)","GHATKESAR","MDL","PVT","NA","COED"],
  [142,"SNIS","SRINIDHI INSTITUTE OF SCI AND TECHNOLOGY","GHATKESAR","MDL","PVT","NA","COED"],
  [143,"SNTI","SCIENT INSTITUTE OF TECHNOLOGY (AUTONOMOUS)","IBRAHIMPATAN","RR","PVT","NA","COED"],
  [144,"SPEC","ST PETERS ENGINEERING COLLEGE (AUTONOMOUS)","MEDCHAL","MDL","PVT","NA","COED"],
  [145,"SPHN","SPHOORTHY ENGINEERING COLLEGE (AUTONOMOUS)","NADERGUL","RR","PVT","NA","COED"],
  [146,"SRHP","SR UNIVERSITY ( FORMERLY S R ENGINEERING COLLEGE)","HASANPARTHY","HNK","PVT","NA","COED"],
  [147,"SRIW","SUMATHI REDDY INST OF TECHNOLOGY FOR WOMEN (AUTONOMOUS)","HASANPARTHY","HNK","PVT","NA","GIRLS"],
  [148,"SRYS","SREYAS INST OF ENGG AND TECHNOLOGY (AUTONOMOUS)","NAGOLE","MDL","PVT","NA","COED"],
  [149,"STLW","STANLEY COLLEGE OF ENGG AND TECHNOLOGY FOR WOMEN (AUTONOMOUS)","ABIDS","HYD","PVT","NA","GIRLS"],
  [150,"SUCE","UNIVERSITY COLLEGE OF ENGINEERING HUSNABAD SATAVAHANA UNIVERSITY","HUSNABAD","SDP","UNIV","NA","COED"],
  [151,"SVES","SRI VENKATESWARA ENGINEERING COLLEGE","SURYAPETA","SRP","PVT","NA","COED"],
  [152,"SVIT","SWAMI VIVEKANANDA INST OF TECHNOLOGY (AUTONOMOUS)","SECUNDERABAD","HYD","PVT","NA","COED"],
  [153,"SVSE","SVS GRP OF INSTNS - SVS INST OF TECH (AUTONOMOUS)","HANAMKONDA","HNK","PVT","NA","COED"],
  [154,"SWET","SHADAN WOMENS COLL OF ENGG AND TECHNOLOGY (AUTONOMOUS)","KHAIRTABAD","HYD","PVT","MUS","GIRLS"],
  [155,"TCEK","TRINITY COLLEGE OF ENGINEERING AND TECHNOLOGY (AUTONOMOUS)","PEDDAPALLY","PDL","PVT","NA","COED"],
  [156,"TCTK","TRINITY COLLEGE OF ENGINEERING AND TECHNOLOGY - AUTONOMOUS","KARIMNAGAR","KRM","PVT","NA","COED"],
  [157,"TKEM","TEEGALA KRISHNA REDDY ENGINEERING COLLEGE (AUTONOMOUS)","MIRPET","RR","PVT","NA","COED"],
  [158,"TKRC","T K R COLLEGE OF ENGG AND TECHNOLOGY (AUTONOMOUS)","MIRPET","RR","PVT","NA","COED"],
  [159,"TPCE","TALLA PADMAVATHI COLL OF ENGINEERING (AUTONOMOUS)","KAZIPET","HNK","PVT","NA","COED"],
  [160,"TRRM","TRR COLLEGE OF TECHNOLOGY","MEERPET","RR","PVT","NA","COED"],
  [161,"TUCE","UNIVERSITY COLLEGE OF ENGINEERING NIZAMABAD","NIZAMABAD","NZB","UNIV","NA","COED"],
  [162,"VAGE","VAAGDEVI COLLEGE OF ENGINEERING (AUTONOMOUS)","WARANGAL","WGL","PVT","NA","COED"],
  [163,"VASV","VASAVI COLLEGE OF ENGINEERING","HYDERABAD","HYD","PVT","NA","COED"],
  [164,"VBIT","VIGNAN BHARATI INSTITUTE OF TECHNOLOGY (AUTONOMOUS)","GHATKESAR","MDL","PVT","NA","COED"],
  [165,"VCET","VISWESWARAYA COLL OF ENGG AND TECHNOLOGY (AUTONOMOUS)","IBRAHIMPATAN","RR","PVT","NA","COED"],
  [166,"VGNT","VIGNAN INSTITUTE OF TECHNOLOGY AND SCI (AUTONOMOUS)","DESHMUKHI","YBG","PVT","NA","COED"],
  [167,"VGSE","VAAGESHWARI COLL OF ENGINEERING (AUTONOMOUS)","KARIMNAGAR","KRM","PVT","NA","COED"],
  [168,"VGWL","VAGDEVI ENGINEERING COLLEGE (AUTONOMOUS)","WARANGAL","WGL","PVT","NA","COED"],
  [169,"VISA","VATHSALYA INSTITUTE OF SCI AND TECHNOLOGY","BHONGIR","YBG","PVT","NA","COED"],
  [170,"VITS","SRI VISHWESWARAYA INST OF TECHNOLOGY AND SCI","MAHABUBNAGAR","MBN","PVT","NA","COED"],
  [171,"VJEC","V N R VIGNANA JYOTHI INSTITUTE OF ENGG AND TECH","BACHUPALLY","MDL","PVT","NA","COED"],
  [172,"VJIT","VIDYAJYOTHI INSTITUTE OF TECHNOLOGY (AUTONOMOUS)","MOINABAD","RR","PVT","NA","COED"],
  [173,"VMEG","VARDHAMAN COLLEGE OF ENGINEERING (AUTONOMOUS)","SHAMSHABAD","RR","PVT","NA","COED"],
  [174,"VMTW","VIGNANS INST OF MANAGEMENT AND TECH FOR WOMEN (AUTONOMOUS)","GHATKESAR","MDL","PVT","NA","GIRLS"],
  [175,"VREC","VIJAYA RURAL ENGINEERING COLLEGE","NIZAMABAD","NZB","PVT","NA","COED"],
  [176,"VRKW","DR VRK WOMENS COLL OF ENGG AND TECHNOLOGY (AUTONOMOUS)","MOINABAD","RR","PVT","MUS","GIRLS"],
  [177,"WESL","CSI WESLEY INST OF TECHNOLOGY AND SCIENCES","SECUNDERABAD","HYD","PVT","CHR","COED"],
  [178,"WITS","WARANGAL INST OF TECHNOLOGY SCIENCE","WARANGAL","HNK","PVT","NA","COED"],
] as InstituteRow[]).map(([no,code,name,place,region,type,minority,mode]) => ({no,code,name,place,region,type,minority,mode}));

export default function InstitutesPage() {
  const [query, setQuery] = useState("");
  const [type, setType] = useState("ALL");
  const filtered = useMemo(() => institutes.filter(i => {
    const q = query.toLowerCase();
    return (!q || `${i.code} ${i.name} ${i.place}`.toLowerCase().includes(q)) && (type === "ALL" || i.type === type);
  }), [query, type]);

  return <main className="min-h-screen bg-[#070707] px-5 py-12 text-white lg:px-8">
    <div className="mx-auto max-w-7xl">
      <div className="mb-8">
        <p className="text-xs font-black uppercase tracking-[.25em] text-[#f4c542]">TGEAPCET Institute Profile</p>
        <h1 className="mt-2 text-4xl font-black tracking-tight md:text-5xl">Institute Profile</h1>
        <p className="mt-3 max-w-2xl text-zinc-500">Browse the institute profile directory with official institute codes, locations, region, type, minority status and mode.</p>
      </div>
      <div className="mb-5 flex flex-col gap-3 md:flex-row">
        <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by institute, code or place..." className="w-full rounded-2xl border border-white/10 bg-white/[.04] px-5 py-3 text-sm outline-none placeholder:text-zinc-600 focus:border-[#f4c542]/50" />
        <select value={type} onChange={e=>setType(e.target.value)} className="rounded-2xl border border-white/10 bg-[#111] px-5 py-3 text-sm font-bold outline-none focus:border-[#f4c542]/50">
          <option value="ALL">All types</option><option value="PVT">Private</option><option value="UNIV">University</option><option value="GOV">Government</option><option value="SF">Self Finance</option>
        </select>
      </div>
      <div className="mb-3 text-sm text-zinc-600">Showing <span className="font-bold text-zinc-300">{filtered.length}</span> of {institutes.length} institutes</div>
      <div className="overflow-hidden rounded-3xl border border-white/10 bg-white/[.02]">
        <div className="overflow-x-auto">
          <table className="w-full min-w-[1050px] border-collapse text-left text-sm">
            <thead className="sticky top-0 bg-[#111] text-[10px] font-black uppercase tracking-[.16em] text-zinc-500">
              <tr><th className="px-4 py-4">#</th><th className="px-4 py-4">Code</th><th className="px-4 py-4 min-w-[380px]">Institute</th><th className="px-4 py-4">Place</th><th className="px-4 py-4">Dist. Region</th><th className="px-4 py-4">Type</th><th className="px-4 py-4">Minority</th><th className="px-4 py-4">Mode</th></tr>
            </thead>
            <tbody className="divide-y divide-white/5">
              {filtered.map(i => <tr key={i.code} className="transition hover:bg-[#f4c542]/[.04]">
                <td className="px-4 py-4 text-zinc-600">{i.no}</td>
                <td className="px-4 py-4"><a href={`https://tgeapcet.nic.in/institute_details.aspx?iCode=${i.code}`} target="_blank" rel="noreferrer" className="font-black text-[#f4c542] hover:underline">{i.code}</a></td>
                <td className="px-4 py-4 font-semibold leading-5 text-zinc-200">{i.name}</td>
                <td className="px-4 py-4 whitespace-nowrap text-zinc-400">{i.place}</td>
                <td className="px-4 py-4 text-zinc-400">{i.region}</td>
                <td className="px-4 py-4"><span className="rounded-full border border-white/10 px-2.5 py-1 text-xs font-bold text-zinc-300">{i.type}</span></td>
                <td className="px-4 py-4 text-zinc-500">{i.minority}</td>
                <td className="px-4 py-4"><span className={i.mode === "GIRLS" ? "font-bold text-pink-300" : "text-zinc-400"}>{i.mode}</span></td>
              </tr>)}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </main>;
}
